# Generated by Django 3.2.8 on 2022-03-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('reportedAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='garbageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'دسته بندی آلودگی',
                'verbose_name_plural': 'دسته بندی آلودگی ها',
            },
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='زمان')),
                ('userAgent', models.CharField(max_length=256, null=True, verbose_name='یوزر ایجنت')),
                ('path', models.CharField(max_length=256, null=True, verbose_name='مسیر')),
                ('isAdminPanel', models.BooleanField(default=False, verbose_name='پنل ادمین')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportedAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('coordinates', models.CharField(max_length=200, verbose_name='مختصات')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('cleanedStatus', models.BooleanField(default=False, verbose_name='پاکیزه شده است؟')),
                ('garbageType', models.ManyToManyField(related_name='category', to='cleanWorld.garbageTypes', verbose_name='دسته بندی')),
                ('reporter', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='گزارش کننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
            },
        ),
        migrations.CreateModel(
            name='cleans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanedAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تمیزشدن')),
                ('cleaner', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمیز کننده')),
                ('report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cleanWorld.reports', verbose_name='مشخصات گزارش دهنده و محل آلودگی')),
            ],
            options={
                'verbose_name': 'تمیز شده',
                'verbose_name_plural': 'تمیز شده ها',
            },
        ),
    ]
