# Generated by Django 3.2.8 on 2022-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWorld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='responseTime',
            field=models.IntegerField(default=2, verbose_name='زمان پاسخ (ثانیه)'),
            preserve_default=False,
        ),
    ]
