# Generated by Django 3.2.8 on 2022-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWorld', '0006_auto_20220327_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='images',
        ),
        migrations.AddField(
            model_name='reports',
            name='images',
            field=models.ManyToManyField(null=True, to='cleanWorld.placeImages', verbose_name='تصاویر'),
        ),
    ]
