# Generated by Django 3.2.8 on 2022-03-27 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanWorld', '0010_alter_placeimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimages',
            name='imageUrl',
            field=models.CharField(max_length=256, null=True, verbose_name='آدرس دراپ باکس'),
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='تصویر'),
        ),
    ]
