# Generated by Django 3.2.8 on 2022-03-29 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanWorld', '0011_auto_20220327_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimages',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='گزارش کننده'),
        ),
    ]
