# Generated by Django 3.2.14 on 2023-06-08 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleanWorld', '0012_placeimages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimages',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده'),
        ),
    ]
